### PR TITLE
fix inconsistences between propagated and unchanged

### LINKED ISSUE #12: Questions about ThreadContextProvider and propagate/unchanged
- I think there's a discrepancy between the naming of `ThreadContextBuilder.propagate` and `ThreadContextBuilder.unchanged`. I think the first should either be `propagated` or the second be `ignore`.
- `ThreadContextBuilder` has `propagate`/`unchanged` but `ManagedExecutionBuilder` only has `context`, which I guess is the equivalent of `propagate`. The name should be coherent, and the functionality to set `unchanged` contexts too.
- The relation between `propagate` and `unchanged` sets, and the implied `cleared` set should be clarified:
-- For `propagate` we take all specified providers plus all the prerequisites, recursively. For `unchanged` the docs say to take all specified providers plus all those that have it as prerequisite, recursively. I wonder why the relation is reversed here? 
-- Once we have both sets, I assume the `cleared` set is the rest of the providers, but I suspect that we have to also make sure that none of the recursive prerequisites of the `cleared` set are within either of the `propagate` or `unchanged` set, right?

### PR DESCRIPTION
**Pull request by njr-11**
pull fixes #12

Renamed `context` on ManagedExecutorConfig to `propagated` in order to match the tense of `unchanged` and to be consistent with ThreadContextBuilder.  Updated docs accordingly.
Corrected explanation for implied prereqs for `unchanged` to match that of `propagated`.
Also removed a TODO from ThreadContext.ALL JavaDoc after placing the appropriate text in the `unchanged` JavaDoc which the TODO referred to. 

Signed-off-by: Nathan Rauh <nathan.rauh@us.ibm.com>

### CODE REVIEW

**Comment by FroMage** [comment]
LGTM. Please merge.

File: api/src/main/java/org/eclipse/microprofile/concurrent/ThreadContextConfig.java [hunk 1]
```diff
@@ -67,6 +67,14 @@
      * in that they are neither captured nor are they propagated or cleared
      * from thread(s) that execute the action or task.</p>
      *
+     * <p>Constants for specifying some of the core context types are provided
+     * on {@link ThreadContext}. Other thread context types must be defined
+     * by the specification that defines the context type or by a related
+     * MicroProfile specification. A <code>ThreadContext</code> must fail to
```
Comment (Emily-Jiang) [inline api/src/main/java/org/eclipse/microprofile/concurrent/ThreadContextConfig.java]: fail with DefinitionException at application startup.
