### PR TITLE
require build/inject to fail when user configures an unavailable context type

### LINKED ISSUE #24: What to do when user specifies a type of thread context that isn't available
It is possible for a user to either directly or indirectly request a type of thread context to be propagated that isn't actually available.  The spec should clarify what happens in this case, so that implementations do not differ.

For example, with the following, assume that a CDI implementation is either not provided by the product or the part of the product that provides CDI is disabled,

```
@Inject @ManagedExecutorConfig(propagated = { ThreadContext.APPLICATION, ThreadContext.SECURITY, ThreadContext.CDI })
ManagedExecutor executor1;

@Inject @ManagedExecutorConfig // the default is the same as above
ManagedExecutor executor2;
```

One option is to simply ignore the types that aren't provided.  The idea here being that if a feature such as CDI isn't provided/usable in the product, that it doesn't matter that we cannot propagate context for it, and we shouldn't trouble the user with an error.  However, this overlooks the possibility that a feature like CDI is provided/usable but the particular CDI implementation is one that didn't contribute a ThreadContextProvider implementation.  Adding a method like managedExecutor/threadContext.propagates(type) to indicate what will actually propagate could help here, but that is also more clutter to the programming model.  Probably the biggest advantage of ignoring types that aren't provided is that the default value of `propagated` will always be usable without causing errors.  Could also include a one-time warning for ignored context.

The other option is to reject the inject/build operation when a thread context type is not provided.  With this, the user is guaranteed that any type they specific will be propagated, and they will be forced to confront errors for types the specify which are not present/enabled.  This will be an advantage when it means detecting a context type for which the user didn't realize a ThreadContextProvider was missing.  If we do this, the defaults for `propagated` will need to be switched, probably to ALL, to avoid causing errors on the basic path where the user has not bothered to configure which specific types.

Please feel free to add further discussion.  On the MP Concurrency call where this was brought up, it sounded like more people were in favor of the second (reject) option.

### PR DESCRIPTION
**Pull request by njr-11**
As discussed in the issue that this fixes #24 , this pull updates JavaDoc to require that an error be raised on ManagedExecutorBuilder.build and ThreadContextBuilder.build when a specified type of thread context is not available.  And it similarly updates JavaDoc on ManagedExecutorConfig/ThreadContextConfig to similarly require that injection fail when a specified type of thread context is not available.

Signed-off-by: Nathan Rauh <nathan.rauh@us.ibm.com>

### CODE REVIEW

**Comment by njr-11** [comment]
@FroMage or @manovotn please review

File: api/src/main/java/org/eclipse/microprofile/concurrent/ManagedExecutorBuilder.java [hunk 1]
```diff
@@ -44,9 +44,11 @@
      * instances.</p>
      *
      * @return new instance of <code>ManagedExecutor</code>.
-     * @throws IllegalArgumentException if the same thread context type is
-     *         present in, or inferred by, both the {@link #cleared} set
-     *         and the {@link #propagated} set.
+     * @throws IllegalArgumentException if a thread context type that is
```
Comment (manovotn) [inline api/src/main/java/org/eclipse/microprofile/concurrent/ManagedExecutorBuilder.java]: I think in this case having the `DefinitionException` would be more appropriate. There are no actual arguments in the method itself, hence `IllegalArgumentException` seems a bit off to me.

File: api/src/main/java/org/eclipse/microprofile/concurrent/ManagedExecutorConfig.java [hunk 2]
```diff
@@ -64,9 +64,10 @@
      * inclusion of the prerequisites, even if not explicitly specified.</p>
      *
      * <p>A <code>ManagedExecutor</code> must fail to inject, raising
-     * <code>DefinitionException</code> on application startup, if the same
-     * context type is implicitly or explicitly included in this set
-     * as well as in the set specified by {@link #propagated}.</p>
+     * <code>DefinitionException</code> on application startup,
```
Comment (manovotn) [inline api/src/main/java/org/eclipse/microprofile/concurrent/ManagedExecutorConfig.java]: By `DefinitionException` I suppose you mean [the one from CDI](https://github.com/cdi-spec/cdi/blob/master/api/src/main/java/javax/enterprise/inject/spi/DefinitionException.java), right? If so, might be worth using a FQCN but I know this is just nitpicking really :)

Comment (njr-11) [reply api/src/main/java/org/eclipse/microprofile/concurrent/ManagedExecutorConfig.java]: Good idea, it's best to be precise here.  I added a commit that that includes the fully qualified class name both here as well as for all mentions of DeploymentException where we were also lacking the package name.

File: api/src/main/java/org/eclipse/microprofile/concurrent/ManagedExecutorBuilder.java (hunk 1 above)
Comment (njr-11) [reply api/src/main/java/org/eclipse/microprofile/concurrent/ManagedExecutorBuilder.java]: We cannot use DefinitionException here because it would cause the builders to have a dependency on CDI and the whole reason the builders were added to the spec was to provide a way to use managed executors/thread context without CDI.  This was requested by Stéphane under https://github.com/eclipse/microprofile-sandbox/issues/18

That said, I'm certain open to a better exception class when the build method detects that an invalid combination of config settings were specified on the builder instance.  I'm sure this isn't the first time a spec with builders has encountered a pattern like this so maybe we can see if there is a precedent for it.

Comment (njr-11) [reply api/src/main/java/org/eclipse/microprofile/concurrent/ManagedExecutorBuilder.java]: After a bit of searching I found the following guidance in [Effective Java](https://books.google.com/books?id=ka2VUBqHiWkC&pg=PA15&lpg=PA15#v=onepage&q&f=false) written by Joshua Bloch: "_If any invariants are violated, the build method should throw an IllegalStateException. The exception's detail message should indicate which invariant is violated._"

I do also see where IllegalArgumentException is used in some existing specs, for example, in the [JsonbBuilder.build](https://static.javadoc.io/javax.json.bind/javax.json.bind-api/1.0/javax/json/bind/JsonbBuilder.html#build--)

It doesn't really concern me which exception type is used here so much as it does clearly defining what the error conditions are.  I can switch it over to IllegalStateException to be consistent with _Effective Java_.

**Comment by njr-11** [comment]
@manovotn I added commits to address both review comments.  Please review again. Thanks!

**Comment by njr-11** [comment]
@manovotn let me know if the added commits address the concerns in your review comments. If so, I'll go ahead and merge this
